// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3ilVBgxKZK9H8EE-nbgTfHGPuTGhjQ8',
    appId: '1:800420041607:web:e902fd5eeaaaa65933f922',
    messagingSenderId: '800420041607',
    projectId: 'khalil-clinec',
    authDomain: 'khalil-clinec.firebaseapp.com',
    storageBucket: 'khalil-clinec.appspot.com',
    measurementId: 'G-RS91JQV38W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0s6HNvS8a0e95XNKigKugKQyMYFdtFps',
    appId: '1:800420041607:android:e7d895996c4b1a1133f922',
    messagingSenderId: '800420041607',
    projectId: 'khalil-clinec',
    storageBucket: 'khalil-clinec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIe76akjqvukuRdJFCtz95aXDdT_klr5k',
    appId: '1:800420041607:ios:e635fdbf184f5cf433f922',
    messagingSenderId: '800420041607',
    projectId: 'khalil-clinec',
    storageBucket: 'khalil-clinec.appspot.com',
    iosBundleId: 'com.example.kalilClinec',
  );
}
